# vim: noexpandtab
#
# -----------------------------------------------------------------------------
#  Makefile: compila e prepara a execução da aplicação
# -----------------------------------------------------------------------------

default:
	@echo "Aguarde enquanto o programa é compilado..."
	@javac -Xlint:deprecation -Xlint:unchecked *.java

clean:
	@echo "Removendo os arquivos binarios do sistema..."
	@rm -rf *.class
